### ISSUE TITLE
Spelling mistake in acknowledgement

### ISSUE THREAD

**Issue by mmhtuda** [HDierend/Data-Quality-Metrics#35]
https://github.com/HDierend/Data-Quality-Metrics/blob/916dc6f352ebcf9ddb7d0b0302b07083a43e6f3e/docs/source/index.rst?plain=1#L12

`Die Authooren;` sollte heißen `Die Autoren`

**Comment by mmhtuda** [comment]
Ich denke prinzipiell kann das "die Autoren" auch weg, wenn die konkreten Namen genannt werden.

**Comment by hgoerner** [comment]
fixed to: Die Autoren
